version: "3.7"


services:
    flask:
        build: ./server
        container_name:  flask
        restart: always
        environment: 
            - APP_NAME=FlaskApp
            - DB_USER=root
            - DB_PASSWORD=sherlockeD123
            - DB_HOST=db
            - DB_PORT=3306
            - DB_NAME=MSCI
        volumes:
            - './server:/app'
        expose:
          - 8080
        depends_on:
          - db

    nginx:
        build: ./nginx
        container_name:  nginx
        restart: always
        ports:
            - "80:80"
    frontend:
        build: ./frontend
        container_name:  frontend
        restart: always
        volumes:
            - './frontend:/frontend'
        ports:
            - "8000:8000"
            - "5000:5000"

    db:
      image: mysql:5.7
      ports:
        - "5001:3306"
      environment:
        MYSQL_ROOT_PASSWORD: sherlockeD123
      volumes:
        - ./db:/docker-entrypoint-initdb.d/:ro
